### PR TITLE
Close span instead of trace on router exception

### PR DESCRIPTION
**Pull request by bforchhammer**
See https://github.com/spandex-project/spandex_phoenix/issues/29#issuecomment-677803596

### CODE REVIEW

**Comment by bforchhammer** [comment]
Well, basically spandex hooks itself up to 2 types of telemtry events: "endpoint" events and "router" events, and the "endpoint start" event is used to start a trace, the "endpoint stop" event is used to attach common metadata as well as close the trace.

The router events (start/stop/exception) are always emitted in between the endpoint start and endpoint stop. The "router start" event starts a new span, and stop/exception should close that span. 

The issue which this PR fixes is that currently the "exception" event closes the full trace instead of just closing the span, which means the "endpoint stop" event doesn't have a closable trace anymore and cannot attach metadata...

**Comment by novaugust** [comment]
Right, but does this then fix the problem where no error traces are showing up in datadog?

(ps: it use to add metadata in exceptions as well, but phx had a bug where they didn't include the conn in an exception so that didn't work! they fixed that in 1.5.4 though)

**Comment by bforchhammer** [comment]
> Right, but does this then fix the problem where no error traces are showing up in datadog?

This PR solves exception traces not having the right tags, which includes the operation (ie. for me exception traces were not grouped together with successful traces for the same resource); I also stumbled on another issue with traces not being "marked as errors", see https://github.com/spandex-project/spandex_phoenix/issues/24#issuecomment-678248231

**Comment by novaugust** [comment]
> (ie. for me exception traces were not grouped together with successful traces for the same resource)

kaching. that makes a ton of sense as the reason why nothing was showing up. i thought no errors were being sent at all, but prompted by your comment i dug into Traces search on datadog and found them. many thanks! excited for this to get in

**Review by GregMefford — APPROVED** [review]
Just checked this against the internal equivalent that I've been using for this and confirmed this is correct! I also see that we have a couple more improvements internally that I can work on contributing here as a separate PR. 🚀

**Comment by GregMefford** [comment]
Oh and thank you all for finding this issue and taking the time to contribute a fix / peer-review each others' work, and everything! Y'all are great! ❤️

**Comment by novaugust** [comment]
could we get a release with this? ❤️ ❤️

**Comment by zachdaniel** [comment]
I'll build one.

**Comment by zachdaniel** [comment]
Released as `1.0.4`
🚀 Thank you for your contribution! 🚀

**Comment by novaugust** [comment]
zach you're a gosh damned hero, thanks man

**Pull request merged**
