### PR TITLE
Better resource name

### PR DESCRIPTION
**Pull request by aselder**
After talking with Jose about a better general solution to this problem, here's what we came up with.

### CODE REVIEW

**Comment by zachdaniel** [comment]
Nice! I didn't know that utility existed. Is it in a newer version of phoenix? If so, we may want to check for its existence with `:erlang.function_exported/3` or something similar, and use the old method if it doesn't exist.

**Comment by aselder** [comment]
Let me do dig and figure out when that `route_info` function was introduced.

**Comment by aselder** [comment]
Based on hexdocs.pm, it looks like `route_info` was introduced Phoenix 1.4.7, which is probably too recent to count on existing. I'll add in the fallback on the old method if it doesn't exist.

**Comment by zachdaniel** [comment]
This looks good otherwise, will merge once that is done.

**Comment by zachdaniel** [comment]
@aselder its been a while since this PR was opened, and the backup method we discussed hasn't been added, so I'm going to close this for now.

**Comment by zachdaniel** [comment]
Feel free to reopen/add the other method.

**Pull request closed without merging**
